package com.crimson.app.crimson.common;

public enum ComplaintCategory {

    HACKING,
    HARASMENT,
    ANTI_PHOTO_AND_VIDEO,
    VOYEURISM,
    ATM_CREDIT_CARD_FRAUD,
    CHILD_PORNOGRAPHY,
    COMPUTER_RELATED_FORGERY,
    COMPUTER_RELATED_IDENTITY,
    THEFT,
    DATA_INTERFERENCE,
    ILLEGAL_ACCESS,
    ONLINE_LIBEL,
    ONLINE_PIRACY,
    ONELINE_SCAM,
    ONLINE_THREAT,
    SEXTORTION,
    WRONGFULLY_REPORTED_ACCOUNT


}

